model:
  best_model: LinearRegression
  feature_sets:
    rfe:
    - sqft
    - bedrooms
    - bathrooms
    - location
    - year_built
    - condition
    - house_age
    - price_per_sqft
    - bed_bath_ratio
  mae: 20501.331161524184
  name: house_price_model
  parameters:
    copy_X: true
    fit_intercept: true
    n_jobs: null
    positive: false
  r2_score: 0.9911482981590555
  target_variable: price
