name: MLOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  mlops-ci:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data processing
        # Make sure this script exists at the path below and accepts these args.
        run: |
          python src/data/run_processing.py \
            --input data/raw/house_data.csv \
            --output data/processed/cleaned_house_data_v1.csv

      - name: Run feature engineering
        run: |
         python src/features/engineer.py  \
          --input data/processed/cleaned_house_data_v1.csv \
          --output data/processed/data_scientists_features.csv  \
          --preprocessor models/trained/preprocessor.pkl


      - name: Setup MLflow Tracking Server (local)
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d --name mlflow-tracking-server -p 5555:5000 ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

      - name: Wait for MLflow
        run: |
          timeout=60
          while ! curl -sSf http://localhost:5555/health > /dev/null 2>&1; do
            echo "Waiting for MLflow..."
            timeout=$((timeout - 5))
            sleep 5
            if [ $timeout -le 0 ]; then echo "MLflow did not start in time"; exit 1; fi
          done
          echo "MLflow is up"

      - name: Train the model
        run: |
          mkdir -p models/trained
          python src/models/train_model.py \
            --config configs/model_config.yaml \
            --data data/processed/data_scientists_features.csv \
            --models-dir models \
            --mlflow-tracking-uri http://localhost:5555

      - name: Cleanup MLflow Tracking Server
        run: |
          docker stop mlflow-tracking-server
          docker rm mlflow-tracking-server 
          docker rmi ghcr.io/mlflow/mlflow:latest

      - name: Run data processing
        run: |
          python src/data/run_processing.py \
            --input data/raw/house_data.csv \
            --output data/processed/cleaned_house_data_v1.csv

      - name: Run feature engineering
        run: |
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data_v1.csv \
            --output data/processed/data_scientists_features.csv \
            --preprocessor models/trained/preprocessor.pkl
