name: MLOps CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run basic tests
        run: |
          echo "Tests will run here."
          echo "Add pytest or other tests in the future."

      - name: Run Data processing Tests
        run: |
          python src/data/run_processing.py --input data/raw/house_data.csv --output data/processed/cleaned_house_data_v1.csv

      - name: Do Feature Engineering
        run: |
          python src/data/run_processing.py --input data/raw/house_data.csv --output data/processed/cleaned_house_data_v1.csv
      

      - name: Setup MLflow Tracking Server
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5000:5000 --name mlflow-tracking-server ghcr.io/mlflow/mlflow:latest \
           mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

      - name: Train the Model
        run: |
          python src/data/run_processing.py \
          --input data/raw/house_data.csv \
          --output data/processed/cleaned_house_data_v1.csv \
          --model-dir models --mlflow-tracking-uri http://localhost:5000
      
      - name: Cleaning up MLflow Tracking Server
        run: |
          docker stop mlflow-tracking-server
          docker rm mlflow-tracking-server
          docker rmi ghcr.io/mlflow/mlflow:latest
          